### ISSUE TITLE
Fancy box getting incorrect link to images

### ISSUE THREAD

**Issue by tobya** [vincent3569/zpBootstrap#2]
Thanks for the amazing theme, its really just what I was looking for.

I have a site https://alldemophotos.cookingisfun.ie/2017/ which I have uploaded your theme to.  It works great, but on some albums when I activate fancybox the urls are incorrect so the images dont load.

This album works fine.

https://alldemophotos.cookingisfun.ie/2017/A%20Week%20at%20Ballymaloe%20Cookery%20School%2C%20Organic%20Farm%20%20Gardens/Mon%203rd%20Apr%202017/

However most other albums display a {{ERROR}}

eg https://alldemophotos.cookingisfun.ie/2017/A%20Week%20at%20Ballymaloe%20Cookery%20School%2C%20Organic%20Farm%20%20Gardens/Tue%204th%20Apr%202017/

The issue seems to be that it is for some reason linking to the images using the full disk path eg

    https://alldemophotos.cookingisfun.ie/home/cookingisfunweb/alldemophotos.cookingisfun.ie/allimages/Gallery/2017/A%20Week%20at%20Ballymaloe%20Cookery%20School%2C%20Organic%20Farm%20%20Gardens/Tue%204th%20Apr%202017/2017-04-04%2016.28.41.jpg

this is invalid due to the part at the front of the url

/home/cookingisfunweb/alldemophotos.cookingisfun.ie/allimages/Gallery/

I am happy to try to fix the issue if you point me in the right direction.

Thanks again.

**Comment by vincent3569** [comment]
hi

you are right, FancyBox display the full image : this is my choice of coding and of using pictures.

I download your picture https://alldemophotos.cookingisfun.ie/2017/A Week at Ballymaloe Cookery School%2C Organic Farm Gardens/Tue 4th Apr 2017/2017-04-04+16.28.16.jpg
Fancy box works on my own server for this picture.

about your issue:
- please read : http://www.zenphoto.org/news/working-with-albums-and-images/
- I suggest you to use seo_cleanup plugin to clean up album and images files name (no space and other weird characters).

**Comment by tobya** [comment]
This issue is the 

    /home/cookingisfunweb/alldemophotos.cookingisfun.ie/allimages/Gallery/

part  of the url, as it is starting with `/home` so providing the full file path on disk rather than url.

You may be correct that it has something to do with the name of the album, but I want to keep the albums with spaces in them.   I am happy to investigate, but unsure how the Fancybox thing works.

This is the error recieved if you tried to get to the image

https://alldemophotos.cookingisfun.ie/home/cookingisfunweb/alldemophotos.cookingisfun.ie/allimages/Gallery/2017/A%20Week%20at%20Ballymaloe%20Cookery%20School%2C%20Organic%20Farm%20%20Gardens/Tue%204th%20Apr%202017/2017-04-04%2016.28.16.jpg

**Comment by tobya** [comment]
On further investigation it seems it is an issue with ZenPhoto so I'll investigate there.
Thanks again.

**Comment by tobya** [comment]
I tracked down the issue it was to do with setting my album to external but it actually being part of the webroot.  I updated my config and it all works now.
