### ISSUE TITLE
zpBootstrap uses a deprecated constructor method declaration

### ISSUE THREAD

**Issue by sbillard** [vincent3569/zpBootstrap#7]
Running zpBootstrap 2.0 under PHP 7 gives the following warning:

> EXCEPTION (8192): "Methods with the same name as their class will not be constructors in a future version of PHP; ThemeOptions has a deprecated constructor" in D:\test_sites\dev\themes\zpBootstrap-2.0\themeoptions.php on line 12

`function ThemeOptions() {` should instead be `function __construct() {`

**Comment by vincent3569** [comment]
hi

this issue have been solved by this commit https://github.com/vincent3569/zpBootstrap/commit/3938864c25a35f83896de0ab4cf04964f4ee3041
